### ISSUE TITLE
Applied collection filters not reflected in the URL

### ISSUE THREAD

**Issue by jordandukart** [jhu-idc/idc-ui-theme#45]
When executing an advanced search an applied collection filter is not reflected in the URL while any applied filters/facets is:

<img width="1573" alt="Screen Shot 2021-06-15 at 2 42 06 PM" src="https://user-images.githubusercontent.com/1337738/122098996-e0f19400-cde7-11eb-9ab3-f5e6c7ae2ce2.png">

Perhaps this done by design intent to not show the `member_of` fields, if so feel free to close this.

**Comment by jabrah** [comment]
This was done intentionally because of time constraints during the initial implementation of advanced search. All of the "advanced search" specific filters follow this behavior: Collections, Language, and Date filters. I would love to revisit this, since it is not a great user experience to see some parts of the UI be initialized while others do not.

This decision was made initially because of how these specific filters are incorporated into the raw search `query` param, which would have made parsing the URL to extract the information for the filters more complicated. Sort of touching on something you had mentioned a bit ago, this could potentially be simplified if we were to refactor how the search REST export is utilized. For example, if it were straightforward to break up the raw Solr query into separate parameters (I think this was mentioned when discussing the query param character limit), then we would have to do far less parsing to get the filter information needed to init the UI.

**Comment by birkland** [comment]
Is this something that would be helpful to bring to Katie's attention, to see if the current behaviour has any UX concerns for her?

**Comment by jabrah** [comment]
Probably a good idea. At least we should make sure Katie and/or Jessica know about it so they can better judge if it's an issue during their testing

**Comment by jordandukart** [comment]
Just as a follow-up looks like the language/date ranges also aren't being reflected.

**Comment by birkland** [comment]
This is a UX question for Jessica, but we don't want it to hold us up.

**Comment by htpvu** [comment]
Close and let jessica brings it up her self if it is a problem.
